/**
 * @file    board.cpp
 * @author  Morthine Xiang (xiang@morthine.com)
 * @brief
 * @version 1.0
 * @date    2023-10-21
 *
 * @copyright SZU-RobotPilots Copyright (c) 2023
 *
 */

#include "main.h"

#include "cmsis_os.h"
#include "adc.h"
#include "can.h"
#include "crc.h"
#include "dma.h"
#include "i2c.h"
#include "rng.h"
#include "spi.h"
#include "tim.h"
#include "gpio.h"
#include "iwdg.h"
#include "sdio.h"
#include "usart.h"
#include "fatfs.h"
#include "usb_device.h"

extern "C" {

void RunTimeTick_Callback(void);
void SystemClock_Config(void);
void MX_FREERTOS_Init(void);

/**
 * @brief  Main program
 * 
 * @return None
 */
int main(void)
{
  /* Syscore Initialize */
  SystemClock_Config();
  HAL_Init();

  /* Hardware Initialize */
  MX_GPIO_Init();
  MX_DMA_Init();
  MX_CAN1_Init();
  MX_CAN2_Init();
  MX_USART2_UART_Init();

  /* FreeRTOS Initialize */
  osKernelInitialize();
  MX_FREERTOS_Init();

  osKernelStart();  // Start thread execution

  return 0;
}



/**
 * @brief  Period elapsed callback in non blocking mode
 * 
 * @param  htim : TIM handle
 * @return None
 * 
 * @note   Please add a prefix "__weak" to the same function in main.c
 *         witch was generated by CubeMX.
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  if (htim->Instance == TIM13)
    RunTimeTick_Callback();

  if (htim->Instance == TIM14)
    HAL_IncTick();

}



/* Timer for Generating FreeRTOS Runtime States */
uint64_t osRunTimeTicks = 0;

void configureTimerForRunTimeStats(void)
{
  MX_TIM13_Init();
  osRunTimeTicks = 0;
  HAL_TIM_Base_Start_IT(&htim13);
}

unsigned long getRunTimeCounterValue(void)
{ return osRunTimeTicks; }

void RunTimeTick_Callback(void)
{ osRunTimeTicks++; }

} // extern "C"
